name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:       # allow manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update README stats
        run: |
          STATS="![Roha's GitHub Stats](https://github-readme-stats.vercel.app/api?username=rohaarslan&show_icons=true&count_private=true&theme=dark&token=${{ secrets.GH_TOKEN }})"
          LANGS="![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=rohaarslan&layout=compact&count_private=true&theme=dark&token=${{ secrets.GH_TOKEN }})"

          # Replace the placeholder in README
          sed -i "/<!-- START_STATS -->/,/<!-- END_STATS -->/c\\
<!-- START_STATS -->\\
$STATS\\
$LANGS\\
<!-- END_STATS -->" README.md

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push
