name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:       # allows manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update README stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          STATS="![Roha's GitHub Stats](https://github-readme-stats.vercel.app/api?username=rohaarslan&show_icons=true&count_private=true&theme=dark&token=$GH_TOKEN)"
          LANGS="![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=rohaarslan&layout=compact&count_private=true&theme=dark&token=$GH_TOKEN)"

          # Use 'awk' to replace lines between markers
          awk -v stats="$STATS" -v langs="$LANGS" '
          BEGIN {inblock=0}
          /<!-- START_STATS -->/ {print; print stats; print langs; inblock=1; next}
          /<!-- END_STATS -->/ {inblock=0}
          !inblock {print}
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push
